### ISSUE TITLE
Win/loss calculation error

### ISSUE THREAD

**Issue by BenGig** [coltoneshaw/3c-portfolio-manager#10]
Here the values from 3CS Quick Stats for comparision, they show the correct value.

![image](https://user-images.githubusercontent.com/5871001/130128037-288ff821-451f-4a3c-b532-4f906a56ecb4.png)

No other deal has this issue.

**Comment by coltoneshaw** [comment]
I believe that I've found the source of this bug. In testing all the data is properly updated on each sync. I'll watch it and do some more testing before releasing it.

**Comment by coltoneshaw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Active Deal data was not properly updating](https://trello.com/c/CH2jsnVe/148-bug-active-deal-data-was-not-properly-updating)
