### ISSUE TITLE
3CPM Web App

### ISSUE THREAD

**Issue by bomzj** [coltoneshaw/3c-portfolio-manager#109]
Please make a web app, so it doesn't require any installs and a way secure as it's sandboxed in browser. You could host the site on Netlify/Vercel/Begin for free and storing API keys in LocalStorage of user browser.

**Comment by coltoneshaw** [comment]
Thanks for your feedback! 

Unfortunately, I probably will not be converting this to a web app anytime soon as a lot of the underlying tech is related to electron and the database is locally stored. 

This tool runs in electron which acts as its own contained browser with limited access to your local environment. It only reads/stores in your application storage specific for the app, and cannot read outside of that. 

The downloads are signed for mac, which adds Apples seal of approval. For Windows they're all ran through WinDefender. The code is open source so you can always see what's in the code and what it's doing. I would also encourage you to run them through any virus scanner you wish and they'll come up clean. 

We have a really large following of community members who use the tool and all vet it themselves as well. No concerns have been brought forward from anyone on security of the electron app.

**Comment by coltoneshaw** [comment]
Since is it open source if anyone wants to convert this to a web app that runs on Docker the PR would be welcomed!
