### ISSUE TITLE
Link to BotNerds discord is invalid

### ISSUE THREAD

**Issue by minibikini** [coltoneshaw/3c-portfolio-manager#112]
**Describe the bug**
The invite link is invalid.

**To Reproduce**
1. Click `Help` menu
2. Click on `BotNerds discord` menu item

**Expected behavior**
The invite link works.

**Screenshots**
<img width="772" alt="Screen Shot 2022-02-09 at 1 20 57 AM" src="https://user-images.githubusercontent.com/439309/153077657-c6924e43-163a-4da7-8d27-0e39de364cdf.png">

**Comment by coltoneshaw** [comment]
Thanks! Go here - https://discord.gg/yWJsKsnn
