### ISSUE TITLE
Date is processed incorrectly on Summary Statistics > Profit per day

### ISSUE THREAD

**Issue by pvdochtend** [coltoneshaw/3c-portfolio-manager#16]
**Describe the bug**
The message "invalid date" is shown.

My computer is set to Dutch Localization (1-9-2021) instead of 9/1/2021
Apparently it's using the local time to display the date that results in an error because 30-8-2021 is processed in as month: 30... 

The last column shows 09-01 but described as 9th of januari.

**Screenshots**
Screenshot added

**Desktop (please complete the following information):**
 - Windows 10
 
![image](https://user-images.githubusercontent.com/3694460/131664323-276001a7-db4c-4cf6-ae16-c9af263b6930.png)

**Comment by coltoneshaw** [comment]
Thanks for opening a ticket! This is actually solved in the next release. I'll see if I can get it out today / tomorrow.
