### ISSUE TITLE
Total in deals

### ISSUE THREAD

**Issue by notio-ca** [coltoneshaw/3c-portfolio-manager#18]
Total in Deals don't match the Volume \ Base column sum

- Second tile in Active deals window

Thanks for this great software!

**Comment by coltoneshaw** [comment]
@notio-ca - Thanks! Can you show me an example? The total in deals is a combination of on_order and total in deals that 3C now shows on their UI. If you hover over the metric it'll breakdown how it's getting that data.

The volume > base should be a sum of total bought volume (in the tool tip).

**Comment by notio-ca** [comment]
@coltoneshaw  Oh there is a tooltips with explosion of the number, that fix it: Not a bug
Thanks a lot!!
