### ISSUE TITLE
Does not work well with BTC Bots

### ISSUE THREAD

**Issue by brhahlen** [coltoneshaw/3c-portfolio-manager#23]
**Describe the bug**
When using the program (which at its core is awesome) to monitor BTC bots, it doesn't work properly, because it won't convert to BTC correctly

**To Reproduce**
1. Go to Settings
2. Click on Currency
3. Choose only BTC
4. Go to Deals (or Stats)
5. Will only see $0.00 listed

***Screenshots***
![image](https://user-images.githubusercontent.com/1798663/132341987-ca655cf3-16ad-4144-908b-ca4317951869.png)

![image](https://user-images.githubusercontent.com/1798663/132342051-eb06d796-e081-477c-a286-9ff7161e8b91.png)

**Expected behavior**
I would expect the calculations to work with BTC as well

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.3.0

**Comment by coltoneshaw** [comment]
Thanks for your feedback! Working to find the best way to handle the decimals that BTC pairs require. Hoping to get this fixed in a few releases.

**Comment by coltoneshaw** [comment]
Need to improve the rounding on the metrics to properly use 6-7 decimal places for BTC.

Goals here:
- [ ] - Dynamic rounding based on the currency that is selected. Each currency has a different number of decimals that should display
- [ ] - Lock the fund filter to only select alike currencies. No mixing of USD / BTC
- [ ] - Find a way to get the current USD price (or use the BTC decimals) to calc risk % and bankroll.

**Comment by brhahlen** [comment]
Cool! If you need some help with testing, let me know :)

**Comment by coltoneshaw** [comment]
<img width="1800" alt="Screen Shot 2021-09-27 at 10 59 09 PM" src="https://user-images.githubusercontent.com/46071821/135015593-07514736-1cdb-4165-b1b7-b3a7d54f2349.png"
<img width="1800" alt="Screen Shot 2021-09-27 at 10 59 26 PM" src="https://user-images.githubusercontent.com/46071821/135015612-0640b8dc-7e44-4fd2-a8f8-e93cc32a6d7e.png">
>

@brhahlen - I've finished implementing crypto rounding into the app. If you'd like to beta test it can you send me a DM to @the_okayest_human on discord

cc: @bradleyBooth

**Comment by brhahlen** [comment]
@coltoneshaw Awesome! Looking forward to test it :)
Have sent a DM on discord (hope it worked)

**Comment by coltoneshaw** [comment]
@brhahlen - can you resend a message or post your username ? Try @the_okayest_human#1680 on discord

**Comment by brhahlen** [comment]
@coltoneshaw I've sent a friend request on Discord, hopefully that works.

**Comment by brhahlen** [comment]
Thanks @coltoneshaw
Looks to be working great with the BTC values!
This can be closed, if you want to!

**Comment by coltoneshaw** [comment]
Fantastic! I'll close this out. Thanks for your help in testing.
