### ISSUE TITLE
Ability to limit dates for stats/performance monitoring

### ISSUE THREAD

**Issue by MonkeyclawTim** [coltoneshaw/3c-portfolio-manager#26]
It would be nice if we could change the date range for stats and performance monitoring directly on those pages instead of having to adjust them in the settings page. This would make the interface much friendlier and make analyzing bot performance quicker.

**Comment by coltoneshaw** [comment]
Thanks for opening this! I'll leave this open so it can be referenced here. However, this is actually on the path right now. There are a few hurdles to accomplish first, but it's coming. It's probably the second most requested feature.

https://trello.com/c/xlHDLbte

**Comment by MonkeyclawTim** [comment]
Woohoo! Thanks!

**Comment by coltoneshaw** [comment]
<img width="1157" alt="Screen Shot 2021-09-30 at 11 25 10 PM" src="https://user-images.githubusercontent.com/46071821/135560656-f0bd18e5-0e2b-4109-961f-6eab5814e6f2.png">

Closed this issue since it's coming in the v0.5 release of this!

**Comment by MonkeyclawTim** [comment]
Awesome, thanks!
