### ISSUE TITLE
Bot name column width

### ISSUE THREAD

**Issue by sgalarneau** [coltoneshaw/3c-portfolio-manager#28]
Having the possibility to extend the column width for bot name (or other columns) so that the name of the bots fits in one line in the active deals window. Or make it so that when you stretch the program window it is the one that extends first.

**Comment by coltoneshaw** [comment]
Thanks for your feedback! Do you mind sending a screenshot of your bot name, I'm curious about the length. I haven't handled extremely long bot names at the moment.

Additionally, how large is your browser window? If you open the dev tools (View => Toggle Dev Tools) and resize it the window side will be on the top right.

Thanks!

**Comment by sgalarneau** [comment]
Sure! Here is an example
![image](https://user-images.githubusercontent.com/6600854/132612845-a0048e4c-21f9-4f50-9029-94387c423126.png)

My browser window size is very variable depending on where I am placing it in my screens but it's usually around 1550x1350

**Comment by coltoneshaw** [comment]
Okay, this will be slotted for the next release. Need to play with how the columns render a bit.

Docs for my reference - https://react-table.tanstack.com/docs/api/useResizeColumns

**Comment by coltoneshaw** [comment]
@sgalarneau - I have a rough solution for this, but with the number of changes that are going into the next release I'm afraid this one will not be able to make it. I'm going to push to get this in the following release, barring any technical limitations I don't see why it won't be.

**Comment by coltoneshaw** [comment]
@sgalarneau - I have added priority to the bot name for the width. It still clips on smaller screens but it's far better right now. If this doesn't work out I'll add clipping to the name so it doesn't wrap so much. I've also added a column selector so you can hide columns to make more room as needed.

https://user-images.githubusercontent.com/46071821/142972253-d6326d05-af03-49be-ad18-cf95a6a56ef4.mov
