### ISSUE TITLE
Coinbase Pro account did not show

### ISSUE THREAD

**Issue by szakee72** [coltoneshaw/3c-portfolio-manager#48]
On the 3commas I have several exchange accounts, Binance, Ftx and Coinbase pro. The API connection was successful, I can see the bots. The Binance and Ftx accounts show up fine, but the Coinbase Pro account does not show up at all, not even in the settings where you can toggle accounts on and off.

**Comment by coltoneshaw** [comment]
@szakee72 - If you navigate to https://3commas.io/accounts do you see the Coinbase Pro account listed? A few additional things:

1. Confirm that you are not in paper trading on the 3Commas UI
2. Try to click `Test API keys` again within the 3cpm settings
3. Does the Coinbase Pro account have a balance?
