### ISSUE TITLE
Deal Allocation in Performance Monitor page does not account for Stats Start Date under settings

### ISSUE THREAD

**Issue by domnuprofesor** [coltoneshaw/3c-portfolio-manager#51]
deals that are before the Stats Start Date show up in Deal Allocation section. I think they should not.

**Comment by coltoneshaw** [comment]
Thanks for letting me know! Do you mind showing an example of this happening?

**Comment by domnuprofesor** [comment]
Sure. Here is a screen shot. 
The deals that have no profit are from a couple of months ago which should be excluded from the chart if the Stats Start Date would apply.

Thank you!

<img width="1458" alt="Screenshot 2021-09-20 at 09 42 06" src="https://user-images.githubusercontent.com/270213/133964647-7c181027-78fd-4cac-8dcf-0cfaa394a1dd.png">

**Comment by coltoneshaw** [comment]
@domnuprofesor - That chart shows deals that have closed from your start date to today. So, for example, if SUSHI was opened July 1st, closed Sept 1st and your filtered start date was Sept 1, you would expect to see that deal.

I tested locally and it's properly filtering deals based on start date, so I have a few quick questions to see if maybe this is a bug or just behavior that can be better explained:

1. What version are you on? Settings > Bottom center.
2. What is your stat start date? Attach a screenshot of that, please.
3. Can you confirm that you do not have a deal closed for those pairs during that window? The easiest way to do this would be to use 3C > History and filter by the pair you're looking at. What is the last closed deal? Attach a screenshot of that as well, please.

Let me know if you have any other questions!

**Comment by domnuprofesor** [comment]
@coltoneshaw 
1. v0.4.1
2. 09/07/2021
3. yes, I can confirm I do not have a deal closed for those pairs during my selected window. So, for those pairs what I did was to close the bots, cancel the deals and managed the coins directly on the exchange.

So, I think those pairs should not show up in the chart since they did not close (they were cancelled).

Does this help?

**Comment by coltoneshaw** [comment]
@domnuprofesor - Thanks! I believe I've fixed this by addressing another bug with canceled / error deals. This should be resolved in the next release of 3cpm. If it's not, we can readdress this. I'll be doing some quick testing as well.

**Comment by coltoneshaw** [comment]
Closing due to no response. If you continue to have this issue just let me know!
