### ISSUE TITLE
Text Issues

### ISSUE THREAD

**Issue by DrGuns4Hands** [coltoneshaw/3c-portfolio-manager#59]
**Active Deals**
Profit should be USD not UTC
![image](https://user-images.githubusercontent.com/4683810/135614394-187eb824-f187-4caa-902f-b3e829dd274f.png)

**Stats/RISK MONITOR**
diving should be dividing when no water is in sight
![image](https://user-images.githubusercontent.com/4683810/135614906-7b1e9ef4-bfa7-4400-bfca-11fd47f269b8.png)

**Bot Planner**
Same as above
![image](https://user-images.githubusercontent.com/4683810/135615238-f686454b-c8d0-4a5f-8a74-ac28eeefccda.png)

**Bot Planner**
Suggestion for Clarification only - I would change "is essentially the average" to "is an approximation of the average"
![image](https://user-images.githubusercontent.com/4683810/135615607-066cabbf-b898-40b9-bb70-8f7f578a8938.png)

**Comment by coltoneshaw** [comment]
Fixed this. The UTC Today is actually telling you the time, not the currency. Clarified that and fixed the others. Thanks!
