### ISSUE TITLE
Readability in dark mode

### ISSUE THREAD

**Issue by BenGig** [coltoneshaw/3c-portfolio-manager#9]
Hi

In dark mode, the green colored numbers are hard to read. May I suggest a slightly brighter red, and the background a bit darker as in one column here?

![image](https://user-images.githubusercontent.com/5871001/130105009-2bc2f8f2-5255-4d6b-828b-8f617172a6b5.png)

**Comment by BenGig** [comment]
One row of course...

**Comment by coltoneshaw** [comment]
<img width="1484" alt="Screen Shot 2021-08-19 at 8 17 17 PM" src="https://user-images.githubusercontent.com/46071821/130159917-e9ad4136-ef4a-492a-98c0-52db3e3655a8.png">
<img width="1512" alt="Screen Shot 2021-08-19 at 8 17 25 PM" src="https://user-images.githubusercontent.com/46071821/130159928-3a2e5525-61e0-41b7-a4fb-33777f141786.png">

I believe converting these to a pill and changing up the red / green solved this.
