### ISSUE TITLE
Unable to test API keys and save profile

### ISSUE THREAD

**Issue by freakfok** [coltoneshaw/3c-portfolio-manager#95]
Hi, I am unable to test api keys. After filling the details, clicking the "test api keys" button doesn't do anything. No pop ups, nothing. When pressing the "save profile" button, it pops up an error that's states "missing an enabled account under reserved funds"

**Screenshots**
![image](https://user-images.githubusercontent.com/61649158/142660267-b92631b2-a948-4ea7-8f60-760fddb3702f.png)
![image](https://user-images.githubusercontent.com/61649158/142660292-4c5845d0-cf05-4057-8218-0cc02fe7ae71.png)

Version 1.00 
Using my PC/Desktop

**Comment by coltoneshaw** [comment]
Thanks for opening a ticket! Below are the docs in case there is an issue with the API keys. Make sure you're using 3Commas keys and not Your exchange. 

Lastly, if the issue continues open the app then menu bar > dev tools > console and click the test button. Let me know if any errors exist. 

https://docs.3cpm.io/configuration/initial-setup

**Comment by freakfok** [comment]
Alright it worked out thank you~
